//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Anleitunge__VrNr__1DE57479", "Versionen", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Versionen), "Anleitungen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Anleitungen), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Downloads__KNr__1BFD2C07", "Kunden", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Kunden), "Downloads", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Downloads), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Downloads__VrNr__1CF15040", "Versionen", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Versionen), "Downloads", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Downloads), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Kunden_Modu__KNr__1A14E395", "Kunden", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Kunden), "Kunden_Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Kunden_Module), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Kunden_Mo__ModNr__1B0907CE", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Module), "Kunden_Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Kunden_Module), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Versionen__MNr__182C9B23", "Mitarbeiter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Mitarbeiter), "Versionen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Versionen), true)]
[assembly: EdmRelationshipAttribute("VerionRLocaleModel", "FK__Versionen__ModNr__1920BF5C", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.ModelsLocale.Module), "Versionen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.ModelsLocale.Versionen), true)]

#endregion

namespace VersionR.ModelsLocale
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class LocaleVersionREntities : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues LocaleVersionREntities-Objekt mithilfe der in Abschnitt 'LocaleVersionREntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public LocaleVersionREntities() : base("name=LocaleVersionREntities", "LocaleVersionREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues LocaleVersionREntities-Objekt.
        /// </summary>
        public LocaleVersionREntities(string connectionString) : base(connectionString, "LocaleVersionREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues LocaleVersionREntities-Objekt.
        /// </summary>
        public LocaleVersionREntities(EntityConnection connection) : base(connection, "LocaleVersionREntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Anleitungen> Anleitungen
        {
            get
            {
                if ((_Anleitungen == null))
                {
                    _Anleitungen = base.CreateObjectSet<Anleitungen>("Anleitungen");
                }
                return _Anleitungen;
            }
        }
        private ObjectSet<Anleitungen> _Anleitungen;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Downloads> Downloads
        {
            get
            {
                if ((_Downloads == null))
                {
                    _Downloads = base.CreateObjectSet<Downloads>("Downloads");
                }
                return _Downloads;
            }
        }
        private ObjectSet<Downloads> _Downloads;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Kunden> Kunden
        {
            get
            {
                if ((_Kunden == null))
                {
                    _Kunden = base.CreateObjectSet<Kunden>("Kunden");
                }
                return _Kunden;
            }
        }
        private ObjectSet<Kunden> _Kunden;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Kunden_Module> Kunden_Module
        {
            get
            {
                if ((_Kunden_Module == null))
                {
                    _Kunden_Module = base.CreateObjectSet<Kunden_Module>("Kunden_Module");
                }
                return _Kunden_Module;
            }
        }
        private ObjectSet<Kunden_Module> _Kunden_Module;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Mitarbeiter> Mitarbeiter
        {
            get
            {
                if ((_Mitarbeiter == null))
                {
                    _Mitarbeiter = base.CreateObjectSet<Mitarbeiter>("Mitarbeiter");
                }
                return _Mitarbeiter;
            }
        }
        private ObjectSet<Mitarbeiter> _Mitarbeiter;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Module> Module
        {
            get
            {
                if ((_Module == null))
                {
                    _Module = base.CreateObjectSet<Module>("Module");
                }
                return _Module;
            }
        }
        private ObjectSet<Module> _Module;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Versionen> Versionen
        {
            get
            {
                if ((_Versionen == null))
                {
                    _Versionen = base.CreateObjectSet<Versionen>("Versionen");
                }
                return _Versionen;
            }
        }
        private ObjectSet<Versionen> _Versionen;

        #endregion
        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Anleitungen'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToAnleitungen(Anleitungen anleitungen)
        {
            base.AddObject("Anleitungen", anleitungen);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Downloads'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToDownloads(Downloads downloads)
        {
            base.AddObject("Downloads", downloads);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Kunden'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToKunden(Kunden kunden)
        {
            base.AddObject("Kunden", kunden);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Kunden_Module'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToKunden_Module(Kunden_Module kunden_Module)
        {
            base.AddObject("Kunden_Module", kunden_Module);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Mitarbeiter'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToMitarbeiter(Mitarbeiter mitarbeiter)
        {
            base.AddObject("Mitarbeiter", mitarbeiter);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Module'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToModule(Module module)
        {
            base.AddObject("Module", module);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Versionen'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToVersionen(Versionen versionen)
        {
            base.AddObject("Versionen", versionen);
        }

        #endregion
    }
    

    #endregion
    
    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Anleitungen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Anleitungen : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Anleitungen-Objekt.
        /// </summary>
        /// <param name="alNr">Anfangswert der Eigenschaft AlNr.</param>
        /// <param name="vrNr">Anfangswert der Eigenschaft VrNr.</param>
        /// <param name="titel">Anfangswert der Eigenschaft Titel.</param>
        /// <param name="dateiName">Anfangswert der Eigenschaft dateiName.</param>
        public static Anleitungen CreateAnleitungen(global::System.Int32 alNr, global::System.Int32 vrNr, global::System.String titel, global::System.String dateiName)
        {
            Anleitungen anleitungen = new Anleitungen();
            anleitungen.AlNr = alNr;
            anleitungen.VrNr = vrNr;
            anleitungen.Titel = titel;
            anleitungen.dateiName = dateiName;
            return anleitungen;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlNr
        {
            get
            {
                return _AlNr;
            }
            set
            {
                if (_AlNr != value)
                {
                    OnAlNrChanging(value);
                    ReportPropertyChanging("AlNr");
                    _AlNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AlNr");
                    OnAlNrChanged();
                }
            }
        }
        private global::System.Int32 _AlNr;
        partial void OnAlNrChanging(global::System.Int32 value);
        partial void OnAlNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrNr
        {
            get
            {
                return _VrNr;
            }
            set
            {
                OnVrNrChanging(value);
                ReportPropertyChanging("VrNr");
                _VrNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VrNr");
                OnVrNrChanged();
            }
        }
        private global::System.Int32 _VrNr;
        partial void OnVrNrChanging(global::System.Int32 value);
        partial void OnVrNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titel
        {
            get
            {
                return _Titel;
            }
            set
            {
                OnTitelChanging(value);
                ReportPropertyChanging("Titel");
                _Titel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titel");
                OnTitelChanged();
            }
        }
        private global::System.String _Titel;
        partial void OnTitelChanging(global::System.String value);
        partial void OnTitelChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Beschreibung
        {
            get
            {
                return _Beschreibung;
            }
            set
            {
                OnBeschreibungChanging(value);
                ReportPropertyChanging("Beschreibung");
                _Beschreibung = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Beschreibung");
                OnBeschreibungChanged();
            }
        }
        private global::System.String _Beschreibung;
        partial void OnBeschreibungChanging(global::System.String value);
        partial void OnBeschreibungChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dateiName
        {
            get
            {
                return _dateiName;
            }
            set
            {
                OndateiNameChanging(value);
                ReportPropertyChanging("dateiName");
                _dateiName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dateiName");
                OndateiNameChanged();
            }
        }
        private global::System.String _dateiName;
        partial void OndateiNameChanging(global::System.String value);
        partial void OndateiNameChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Anleitunge__VrNr__1DE57479", "Versionen")]
        public Versionen Versionen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Versionen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Versionen").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Versionen> VersionenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Versionen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Versionen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Versionen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Downloads")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Downloads : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Downloads-Objekt.
        /// </summary>
        /// <param name="dlNr">Anfangswert der Eigenschaft DlNr.</param>
        /// <param name="dlDatum">Anfangswert der Eigenschaft DlDatum.</param>
        /// <param name="vrNr">Anfangswert der Eigenschaft VrNr.</param>
        /// <param name="kNr">Anfangswert der Eigenschaft KNr.</param>
        public static Downloads CreateDownloads(global::System.Int32 dlNr, global::System.DateTime dlDatum, global::System.Int32 vrNr, global::System.Int32 kNr)
        {
            Downloads downloads = new Downloads();
            downloads.DlNr = dlNr;
            downloads.DlDatum = dlDatum;
            downloads.VrNr = vrNr;
            downloads.KNr = kNr;
            return downloads;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DlNr
        {
            get
            {
                return _DlNr;
            }
            set
            {
                if (_DlNr != value)
                {
                    OnDlNrChanging(value);
                    ReportPropertyChanging("DlNr");
                    _DlNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DlNr");
                    OnDlNrChanged();
                }
            }
        }
        private global::System.Int32 _DlNr;
        partial void OnDlNrChanging(global::System.Int32 value);
        partial void OnDlNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DlDatum
        {
            get
            {
                return _DlDatum;
            }
            set
            {
                OnDlDatumChanging(value);
                ReportPropertyChanging("DlDatum");
                _DlDatum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DlDatum");
                OnDlDatumChanged();
            }
        }
        private global::System.DateTime _DlDatum;
        partial void OnDlDatumChanging(global::System.DateTime value);
        partial void OnDlDatumChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrNr
        {
            get
            {
                return _VrNr;
            }
            set
            {
                OnVrNrChanging(value);
                ReportPropertyChanging("VrNr");
                _VrNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VrNr");
                OnVrNrChanged();
            }
        }
        private global::System.Int32 _VrNr;
        partial void OnVrNrChanging(global::System.Int32 value);
        partial void OnVrNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KNr
        {
            get
            {
                return _KNr;
            }
            set
            {
                OnKNrChanging(value);
                ReportPropertyChanging("KNr");
                _KNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KNr");
                OnKNrChanged();
            }
        }
        private global::System.Int32 _KNr;
        partial void OnKNrChanging(global::System.Int32 value);
        partial void OnKNrChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Downloads__KNr__1BFD2C07", "Kunden")]
        public Kunden Kunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Kunden").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Kunden").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kunden> KundenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Kunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kunden>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Kunden", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Downloads__VrNr__1CF15040", "Versionen")]
        public Versionen Versionen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Versionen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Versionen").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Versionen> VersionenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Versionen>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Versionen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Versionen>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Versionen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Kunden")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kunden : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Kunden-Objekt.
        /// </summary>
        /// <param name="kNr">Anfangswert der Eigenschaft KNr.</param>
        /// <param name="nickName">Anfangswert der Eigenschaft NickName.</param>
        /// <param name="email">Anfangswert der Eigenschaft Email.</param>
        /// <param name="pwHash">Anfangswert der Eigenschaft PwHash.</param>
        public static Kunden CreateKunden(global::System.Int32 kNr, global::System.String nickName, global::System.String email, global::System.String pwHash)
        {
            Kunden kunden = new Kunden();
            kunden.KNr = kNr;
            kunden.NickName = nickName;
            kunden.Email = email;
            kunden.PwHash = pwHash;
            return kunden;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KNr
        {
            get
            {
                return _KNr;
            }
            set
            {
                if (_KNr != value)
                {
                    OnKNrChanging(value);
                    ReportPropertyChanging("KNr");
                    _KNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KNr");
                    OnKNrChanged();
                }
            }
        }
        private global::System.Int32 _KNr;
        partial void OnKNrChanging(global::System.Int32 value);
        partial void OnKNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();
    
        /// <summary>
        /// Das Passwort in KlarText wird verschlüsselt und danach in der Datenbank abgelegt!!
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PwHash
        {
            get
            {
                return _PwHash;
            }
            set
            {
                OnPwHashChanging(value);
                ReportPropertyChanging("PwHash");
                _PwHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PwHash");
                OnPwHashChanged();
            }
        }

        private global::System.String _PwHash;
        partial void OnPwHashChanging(global::System.String value);
        partial void OnPwHashChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Downloads__KNr__1BFD2C07", "Downloads")]
        public EntityCollection<Downloads> Downloads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Downloads>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Downloads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Downloads>("VerionRLocaleModel.FK__Downloads__KNr__1BFD2C07", "Downloads", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Kunden_Modu__KNr__1A14E395", "Kunden_Module")]
        public EntityCollection<Kunden_Module> Kunden_Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kunden_Module>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden_Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kunden_Module>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden_Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Kunden_Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kunden_Module : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Kunden_Module-Objekt.
        /// </summary>
        /// <param name="auftragNr">Anfangswert der Eigenschaft AuftragNr.</param>
        /// <param name="kNr">Anfangswert der Eigenschaft KNr.</param>
        /// <param name="modNr">Anfangswert der Eigenschaft ModNr.</param>
        /// <param name="kaufDatum">Anfangswert der Eigenschaft KaufDatum.</param>
        /// <param name="endDatum">Anfangswert der Eigenschaft EndDatum.</param>
        public static Kunden_Module CreateKunden_Module(global::System.Int32 auftragNr, global::System.Int32 kNr, global::System.Int32 modNr, global::System.DateTime kaufDatum, global::System.DateTime endDatum)
        {
            Kunden_Module kunden_Module = new Kunden_Module();
            kunden_Module.AuftragNr = auftragNr;
            kunden_Module.KNr = kNr;
            kunden_Module.ModNr = modNr;
            kunden_Module.KaufDatum = kaufDatum;
            kunden_Module.EndDatum = endDatum;
            return kunden_Module;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuftragNr
        {
            get
            {
                return _AuftragNr;
            }
            set
            {
                if (_AuftragNr != value)
                {
                    OnAuftragNrChanging(value);
                    ReportPropertyChanging("AuftragNr");
                    _AuftragNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuftragNr");
                    OnAuftragNrChanged();
                }
            }
        }
        private global::System.Int32 _AuftragNr;
        partial void OnAuftragNrChanging(global::System.Int32 value);
        partial void OnAuftragNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KNr
        {
            get
            {
                return _KNr;
            }
            set
            {
                OnKNrChanging(value);
                ReportPropertyChanging("KNr");
                _KNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KNr");
                OnKNrChanged();
            }
        }
        private global::System.Int32 _KNr;
        partial void OnKNrChanging(global::System.Int32 value);
        partial void OnKNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModNr
        {
            get
            {
                return _ModNr;
            }
            set
            {
                OnModNrChanging(value);
                ReportPropertyChanging("ModNr");
                _ModNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModNr");
                OnModNrChanged();
            }
        }
        private global::System.Int32 _ModNr;
        partial void OnModNrChanging(global::System.Int32 value);
        partial void OnModNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime KaufDatum
        {
            get
            {
                return _KaufDatum;
            }
            set
            {
                OnKaufDatumChanging(value);
                ReportPropertyChanging("KaufDatum");
                _KaufDatum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KaufDatum");
                OnKaufDatumChanged();
            }
        }
        private global::System.DateTime _KaufDatum;
        partial void OnKaufDatumChanging(global::System.DateTime value);
        partial void OnKaufDatumChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDatum
        {
            get
            {
                return _EndDatum;
            }
            set
            {
                OnEndDatumChanging(value);
                ReportPropertyChanging("EndDatum");
                _EndDatum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDatum");
                OnEndDatumChanged();
            }
        }
        private global::System.DateTime _EndDatum;
        partial void OnEndDatumChanging(global::System.DateTime value);
        partial void OnEndDatumChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Kunden_Modu__KNr__1A14E395", "Kunden")]
        public Kunden Kunden
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kunden> KundenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kunden>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kunden>("VerionRLocaleModel.FK__Kunden_Modu__KNr__1A14E395", "Kunden", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Kunden_Mo__ModNr__1B0907CE", "Module")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Module").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Mitarbeiter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mitarbeiter : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Mitarbeiter-Objekt.
        /// </summary>
        /// <param name="mNr">Anfangswert der Eigenschaft MNr.</param>
        /// <param name="nickName">Anfangswert der Eigenschaft NickName.</param>
        /// <param name="eMail">Anfangswert der Eigenschaft EMail.</param>
        /// <param name="pwHash">Anfangswert der Eigenschaft PwHash.</param>
        public static Mitarbeiter CreateMitarbeiter(global::System.Int32 mNr, global::System.String nickName, global::System.String eMail, global::System.String pwHash)
        {
            Mitarbeiter mitarbeiter = new Mitarbeiter();
            mitarbeiter.MNr = mNr;
            mitarbeiter.NickName = nickName;
            mitarbeiter.EMail = eMail;
            
            mitarbeiter.PwHash = pwHash;
            return mitarbeiter;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MNr
        {
            get
            {
                return _MNr;
            }
            set
            {
                if (_MNr != value)
                {
                    OnMNrChanging(value);
                    ReportPropertyChanging("MNr");
                    _MNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MNr");
                    OnMNrChanged();
                }
            }
        }
        private global::System.Int32 _MNr;
        partial void OnMNrChanging(global::System.Int32 value);
        partial void OnMNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PwHash
        {
            get
            {
                return _PwHash;
            }
            set
            {
                OnPwHashChanging(value);
                ReportPropertyChanging("PwHash");
                _PwHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PwHash");
                OnPwHashChanged();
            }
        }
        private global::System.String _PwHash;
        partial void OnPwHashChanging(global::System.String value);
        partial void OnPwHashChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Versionen__MNr__182C9B23", "Versionen")]
        public EntityCollection<Versionen> Versionen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Versionen>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Versionen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Versionen>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Versionen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Module-Objekt.
        /// </summary>
        /// <param name="modNr">Anfangswert der Eigenschaft ModNr.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="jahresPreis">Anfangswert der Eigenschaft JahresPreis.</param>
        public static Module CreateModule(global::System.Int32 modNr, global::System.String name, global::System.Decimal jahresPreis)
        {
            Module module = new Module();
            module.ModNr = modNr;
            module.Name = name;
            module.JahresPreis = jahresPreis;
            return module;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModNr
        {
            get
            {
                return _ModNr;
            }
            set
            {
                if (_ModNr != value)
                {
                    OnModNrChanging(value);
                    ReportPropertyChanging("ModNr");
                    _ModNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModNr");
                    OnModNrChanged();
                }
            }
        }
        private global::System.Int32 _ModNr;
        partial void OnModNrChanging(global::System.Int32 value);
        partial void OnModNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal JahresPreis
        {
            get
            {
                return _JahresPreis;
            }
            set
            {
                OnJahresPreisChanging(value);
                ReportPropertyChanging("JahresPreis");
                _JahresPreis = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JahresPreis");
                OnJahresPreisChanged();
            }
        }
        private global::System.Decimal _JahresPreis;
        partial void OnJahresPreisChanging(global::System.Decimal value);
        partial void OnJahresPreisChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Kunden_Mo__ModNr__1B0907CE", "Kunden_Module")]
        public EntityCollection<Kunden_Module> Kunden_Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kunden_Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Kunden_Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kunden_Module>("VerionRLocaleModel.FK__Kunden_Mo__ModNr__1B0907CE", "Kunden_Module", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Versionen__ModNr__1920BF5C", "Versionen")]
        public EntityCollection<Versionen> Versionen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Versionen>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Versionen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Versionen>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Versionen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VerionRLocaleModel", Name="Versionen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Versionen : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Versionen-Objekt.
        /// </summary>
        /// <param name="vrNr">Anfangswert der Eigenschaft VrNr.</param>
        /// <param name="relase">Anfangswert der Eigenschaft Relase.</param>
        /// <param name="subRelease">Anfangswert der Eigenschaft SubRelease.</param>
        /// <param name="buildNr">Anfangswert der Eigenschaft BuildNr.</param>
        /// <param name="plattform">Anfangswert der Eigenschaft Plattform.</param>
        /// <param name="dateiName">Anfangswert der Eigenschaft DateiName.</param>
        /// <param name="erscheinungsDatum">Anfangswert der Eigenschaft ErscheinungsDatum.</param>
        /// <param name="mNr">Anfangswert der Eigenschaft MNr.</param>
        /// <param name="modNr">Anfangswert der Eigenschaft ModNr.</param>
        public static Versionen CreateVersionen(global::System.Int32 vrNr, global::System.Byte relase, global::System.Byte subRelease, global::System.String buildNr, global::System.String plattform, global::System.String dateiName, global::System.DateTime erscheinungsDatum, global::System.Int32 mNr, global::System.Int32 modNr)
        {
            Versionen versionen = new Versionen();
            versionen.VrNr = vrNr;
            versionen.Relase = relase;
            versionen.SubRelease = subRelease;
            versionen.BuildNr = buildNr;
            versionen.Plattform = plattform;
            versionen.DateiName = dateiName;
            versionen.ErscheinungsDatum = erscheinungsDatum;
            versionen.MNr = mNr;
            versionen.ModNr = modNr;
            return versionen;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrNr
        {
            get
            {
                return _VrNr;
            }
            set
            {
                if (_VrNr != value)
                {
                    OnVrNrChanging(value);
                    ReportPropertyChanging("VrNr");
                    _VrNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VrNr");
                    OnVrNrChanged();
                }
            }
        }
        private global::System.Int32 _VrNr;
        partial void OnVrNrChanging(global::System.Int32 value);
        partial void OnVrNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Relase
        {
            get
            {
                return _Relase;
            }
            set
            {
                OnRelaseChanging(value);
                ReportPropertyChanging("Relase");
                _Relase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Relase");
                OnRelaseChanged();
            }
        }
        private global::System.Byte _Relase;
        partial void OnRelaseChanging(global::System.Byte value);
        partial void OnRelaseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte SubRelease
        {
            get
            {
                return _SubRelease;
            }
            set
            {
                OnSubReleaseChanging(value);
                ReportPropertyChanging("SubRelease");
                _SubRelease = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubRelease");
                OnSubReleaseChanged();
            }
        }
        private global::System.Byte _SubRelease;
        partial void OnSubReleaseChanging(global::System.Byte value);
        partial void OnSubReleaseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuildNr
        {
            get
            {
                return _BuildNr;
            }
            set
            {
                OnBuildNrChanging(value);
                ReportPropertyChanging("BuildNr");
                _BuildNr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuildNr");
                OnBuildNrChanged();
            }
        }
        private global::System.String _BuildNr;
        partial void OnBuildNrChanging(global::System.String value);
        partial void OnBuildNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Plattform
        {
            get
            {
                return _Plattform;
            }
            set
            {
                OnPlattformChanging(value);
                ReportPropertyChanging("Plattform");
                _Plattform = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Plattform");
                OnPlattformChanged();
            }
        }
        private global::System.String _Plattform;
        partial void OnPlattformChanging(global::System.String value);
        partial void OnPlattformChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateiName
        {
            get
            {
                return _DateiName;
            }
            set
            {
                OnDateiNameChanging(value);
                ReportPropertyChanging("DateiName");
                _DateiName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateiName");
                OnDateiNameChanged();
            }
        }
        private global::System.String _DateiName;
        partial void OnDateiNameChanging(global::System.String value);
        partial void OnDateiNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Beschreibung
        {
            get
            {
                return _Beschreibung;
            }
            set
            {
                OnBeschreibungChanging(value);
                ReportPropertyChanging("Beschreibung");
                _Beschreibung = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Beschreibung");
                OnBeschreibungChanged();
            }
        }
        private global::System.String _Beschreibung;
        partial void OnBeschreibungChanging(global::System.String value);
        partial void OnBeschreibungChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ErscheinungsDatum
        {
            get
            {
                return _ErscheinungsDatum;
            }
            set
            {
                OnErscheinungsDatumChanging(value);
                ReportPropertyChanging("ErscheinungsDatum");
                _ErscheinungsDatum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErscheinungsDatum");
                OnErscheinungsDatumChanged();
            }
        }
        private global::System.DateTime _ErscheinungsDatum;
        partial void OnErscheinungsDatumChanging(global::System.DateTime value);
        partial void OnErscheinungsDatumChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MNr
        {
            get
            {
                return _MNr;
            }
            set
            {
                OnMNrChanging(value);
                ReportPropertyChanging("MNr");
                _MNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MNr");
                OnMNrChanged();
            }
        }
        private global::System.Int32 _MNr;
        partial void OnMNrChanging(global::System.Int32 value);
        partial void OnMNrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModNr
        {
            get
            {
                return _ModNr;
            }
            set
            {
                OnModNrChanging(value);
                ReportPropertyChanging("ModNr");
                _ModNr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModNr");
                OnModNrChanged();
            }
        }
        private global::System.Int32 _ModNr;
        partial void OnModNrChanging(global::System.Int32 value);
        partial void OnModNrChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Anleitunge__VrNr__1DE57479", "Anleitungen")]
        public EntityCollection<Anleitungen> Anleitungen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Anleitungen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Anleitungen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Anleitungen>("VerionRLocaleModel.FK__Anleitunge__VrNr__1DE57479", "Anleitungen", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Downloads__VrNr__1CF15040", "Downloads")]
        public EntityCollection<Downloads> Downloads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Downloads>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Downloads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Downloads>("VerionRLocaleModel.FK__Downloads__VrNr__1CF15040", "Downloads", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Versionen__MNr__182C9B23", "Mitarbeiter")]
        public Mitarbeiter Mitarbeiter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mitarbeiter>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Mitarbeiter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mitarbeiter>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Mitarbeiter").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mitarbeiter> MitarbeiterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mitarbeiter>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Mitarbeiter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mitarbeiter>("VerionRLocaleModel.FK__Versionen__MNr__182C9B23", "Mitarbeiter", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VerionRLocaleModel", "FK__Versionen__ModNr__1920BF5C", "Module")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Module").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("VerionRLocaleModel.FK__Versionen__ModNr__1920BF5C", "Module", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
