//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Customer___ModId__60924D76", "Modules", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.Module), "Customer_Modules", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Customer_Modules), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Customer_M__CmId__5F9E293D", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.User), "Customer_Modules", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Customer_Modules), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Downloads__CmId__627A95E8", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.User), "Downloads", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Download), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Downloads__VrId__618671AF", "Versions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.Version), "Downloads", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Download), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Manuals__VrId__636EBA21", "Versions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.Version), "Manuals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Manual), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Versions__ModId__5EAA0504", "Modules", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.Module), "Versions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Version), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Users__RId__6462DE5A", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.Role), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.User), true)]
[assembly: EdmRelationshipAttribute("VersionR_Entities", "FK__Versions__EmId__5DB5E0CB", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VersionR.Models.User), "Versions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VersionR.Models.Version), true)]

#endregion

namespace VersionR.Models
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class VersionR : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues VersionR-Objekt mithilfe der in Abschnitt 'VersionR' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public VersionR() : base("name=VersionR", "VersionR")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues VersionR-Objekt.
        /// </summary>
        public VersionR(string connectionString) : base(connectionString, "VersionR")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues VersionR-Objekt.
        /// </summary>
        public VersionR(EntityConnection connection) : base(connection, "VersionR")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Customer_Modules> Customer_Modules
        {
            get
            {
                if ((_Customer_Modules == null))
                {
                    _Customer_Modules = base.CreateObjectSet<Customer_Modules>("Customer_Modules");
                }
                return _Customer_Modules;
            }
        }
        private ObjectSet<Customer_Modules> _Customer_Modules;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Download> Downloads
        {
            get
            {
                if ((_Downloads == null))
                {
                    _Downloads = base.CreateObjectSet<Download>("Downloads");
                }
                return _Downloads;
            }
        }
        private ObjectSet<Download> _Downloads;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Manual> Manuals
        {
            get
            {
                if ((_Manuals == null))
                {
                    _Manuals = base.CreateObjectSet<Manual>("Manuals");
                }
                return _Manuals;
            }
        }
        private ObjectSet<Manual> _Manuals;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Version> Versions
        {
            get
            {
                if ((_Versions == null))
                {
                    _Versions = base.CreateObjectSet<Version>("Versions");
                }
                return _Versions;
            }
        }
        private ObjectSet<Version> _Versions;

        #endregion

        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Customer_Modules'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToCustomer_Modules(Customer_Modules customer_Modules)
        {
            base.AddObject("Customer_Modules", customer_Modules);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Downloads'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToDownloads(Download download)
        {
            base.AddObject("Downloads", download);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Manuals'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToManuals(Manual manual)
        {
            base.AddObject("Manuals", manual);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Modules'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Roles'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Users'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Versions'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToVersions(Version version)
        {
            base.AddObject("Versions", version);
        }

        #endregion

    }

    #endregion

    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Customer_Modules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer_Modules : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Customer_Modules-Objekt.
        /// </summary>
        /// <param name="orderId">Anfangswert der Eigenschaft OrderId.</param>
        /// <param name="cmId">Anfangswert der Eigenschaft CmId.</param>
        /// <param name="modId">Anfangswert der Eigenschaft ModId.</param>
        /// <param name="buyDate">Anfangswert der Eigenschaft BuyDate.</param>
        /// <param name="expiryDate">Anfangswert der Eigenschaft ExpiryDate.</param>
        public static Customer_Modules CreateCustomer_Modules(global::System.Int32 orderId, global::System.Int32 cmId, global::System.Int32 modId, global::System.DateTime buyDate, global::System.DateTime expiryDate)
        {
            Customer_Modules customer_Modules = new Customer_Modules();
            customer_Modules.OrderId = orderId;
            customer_Modules.CmId = cmId;
            customer_Modules.ModId = modId;
            customer_Modules.BuyDate = buyDate;
            customer_Modules.ExpiryDate = expiryDate;
            return customer_Modules;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CmId
        {
            get
            {
                return _CmId;
            }
            set
            {
                OnCmIdChanging(value);
                ReportPropertyChanging("CmId");
                _CmId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CmId");
                OnCmIdChanged();
            }
        }
        private global::System.Int32 _CmId;
        partial void OnCmIdChanging(global::System.Int32 value);
        partial void OnCmIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModId
        {
            get
            {
                return _ModId;
            }
            set
            {
                OnModIdChanging(value);
                ReportPropertyChanging("ModId");
                _ModId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModId");
                OnModIdChanged();
            }
        }
        private global::System.Int32 _ModId;
        partial void OnModIdChanging(global::System.Int32 value);
        partial void OnModIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BuyDate
        {
            get
            {
                return _BuyDate;
            }
            set
            {
                OnBuyDateChanging(value);
                ReportPropertyChanging("BuyDate");
                _BuyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyDate");
                OnBuyDateChanged();
            }
        }
        private global::System.DateTime _BuyDate;
        partial void OnBuyDateChanging(global::System.DateTime value);
        partial void OnBuyDateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpiryDate
        {
            get
            {
                return _ExpiryDate;
            }
            set
            {
                OnExpiryDateChanging(value);
                ReportPropertyChanging("ExpiryDate");
                _ExpiryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpiryDate");
                OnExpiryDateChanged();
            }
        }
        private global::System.DateTime _ExpiryDate;
        partial void OnExpiryDateChanging(global::System.DateTime value);
        partial void OnExpiryDateChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Customer___ModId__60924D76", "Modules")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Customer___ModId__60924D76", "Modules").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Customer___ModId__60924D76", "Modules").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Customer___ModId__60924D76", "Modules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("VersionR_Entities.FK__Customer___ModId__60924D76", "Modules", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Customer_M__CmId__5F9E293D", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Users").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Download")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Download : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Download-Objekt.
        /// </summary>
        /// <param name="dlId">Anfangswert der Eigenschaft DlId.</param>
        /// <param name="dlDate">Anfangswert der Eigenschaft DlDate.</param>
        /// <param name="vrId">Anfangswert der Eigenschaft VrId.</param>
        /// <param name="cmId">Anfangswert der Eigenschaft CmId.</param>
        public static Download CreateDownload(global::System.Int32 dlId, global::System.DateTime dlDate, global::System.Int32 vrId, global::System.Int32 cmId)
        {
            Download download = new Download();
            download.DlId = dlId;
            download.DlDate = dlDate;
            download.VrId = vrId;
            download.CmId = cmId;
            return download;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DlId
        {
            get
            {
                return _DlId;
            }
            set
            {
                if (_DlId != value)
                {
                    OnDlIdChanging(value);
                    ReportPropertyChanging("DlId");
                    _DlId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DlId");
                    OnDlIdChanged();
                }
            }
        }
        private global::System.Int32 _DlId;
        partial void OnDlIdChanging(global::System.Int32 value);
        partial void OnDlIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DlDate
        {
            get
            {
                return _DlDate;
            }
            set
            {
                OnDlDateChanging(value);
                ReportPropertyChanging("DlDate");
                _DlDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DlDate");
                OnDlDateChanged();
            }
        }
        private global::System.DateTime _DlDate;
        partial void OnDlDateChanging(global::System.DateTime value);
        partial void OnDlDateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrId
        {
            get
            {
                return _VrId;
            }
            set
            {
                OnVrIdChanging(value);
                ReportPropertyChanging("VrId");
                _VrId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VrId");
                OnVrIdChanged();
            }
        }
        private global::System.Int32 _VrId;
        partial void OnVrIdChanging(global::System.Int32 value);
        partial void OnVrIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CmId
        {
            get
            {
                return _CmId;
            }
            set
            {
                OnCmIdChanging(value);
                ReportPropertyChanging("CmId");
                _CmId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CmId");
                OnCmIdChanged();
            }
        }
        private global::System.Int32 _CmId;
        partial void OnCmIdChanging(global::System.Int32 value);
        partial void OnCmIdChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Downloads__CmId__627A95E8", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Users").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Downloads__VrId__618671AF", "Versions")]
        public Version Version
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Versions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Versions").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Version> VersionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Versions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Version>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Versions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Manual")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manual : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Manual-Objekt.
        /// </summary>
        /// <param name="mId">Anfangswert der Eigenschaft MId.</param>
        /// <param name="vrId">Anfangswert der Eigenschaft VrId.</param>
        /// <param name="title">Anfangswert der Eigenschaft Title.</param>
        /// <param name="filename">Anfangswert der Eigenschaft Filename.</param>
        public static Manual CreateManual(global::System.Int32 mId, global::System.Int32 vrId, global::System.String title, global::System.String filename)
        {
            Manual manual = new Manual();
            manual.MId = mId;
            manual.VrId = vrId;
            manual.Title = title;
            manual.Filename = filename;
            return manual;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MId
        {
            get
            {
                return _MId;
            }
            set
            {
                if (_MId != value)
                {
                    OnMIdChanging(value);
                    ReportPropertyChanging("MId");
                    _MId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MId");
                    OnMIdChanged();
                }
            }
        }
        private global::System.Int32 _MId;
        partial void OnMIdChanging(global::System.Int32 value);
        partial void OnMIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrId
        {
            get
            {
                return _VrId;
            }
            set
            {
                OnVrIdChanging(value);
                ReportPropertyChanging("VrId");
                _VrId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VrId");
                OnVrIdChanged();
            }
        }
        private global::System.Int32 _VrId;
        partial void OnVrIdChanging(global::System.Int32 value);
        partial void OnVrIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Filename
        {
            get
            {
                return _Filename;
            }
            set
            {
                OnFilenameChanging(value);
                ReportPropertyChanging("Filename");
                _Filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Filename");
                OnFilenameChanged();
            }
        }
        private global::System.String _Filename;
        partial void OnFilenameChanging(global::System.String value);
        partial void OnFilenameChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Manuals__VrId__636EBA21", "Versions")]
        public Version Version
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Versions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Versions").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Version> VersionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Version>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Versions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Version>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Versions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Module-Objekt.
        /// </summary>
        /// <param name="modId">Anfangswert der Eigenschaft ModId.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="pricePerYear">Anfangswert der Eigenschaft PricePerYear.</param>
        public static Module CreateModule(global::System.Int32 modId, global::System.String name, global::System.Decimal pricePerYear)
        {
            Module module = new Module();
            module.ModId = modId;
            module.Name = name;
            module.PricePerYear = pricePerYear;
            return module;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModId
        {
            get
            {
                return _ModId;
            }
            set
            {
                if (_ModId != value)
                {
                    OnModIdChanging(value);
                    ReportPropertyChanging("ModId");
                    _ModId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModId");
                    OnModIdChanged();
                }
            }
        }
        private global::System.Int32 _ModId;
        partial void OnModIdChanging(global::System.Int32 value);
        partial void OnModIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PricePerYear
        {
            get
            {
                return _PricePerYear;
            }
            set
            {
                OnPricePerYearChanging(value);
                ReportPropertyChanging("PricePerYear");
                _PricePerYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PricePerYear");
                OnPricePerYearChanged();
            }
        }
        private global::System.Decimal _PricePerYear;
        partial void OnPricePerYearChanging(global::System.Decimal value);
        partial void OnPricePerYearChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Customer___ModId__60924D76", "Customer_Modules")]
        public EntityCollection<Customer_Modules> Customer_Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer_Modules>("VersionR_Entities.FK__Customer___ModId__60924D76", "Customer_Modules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer_Modules>("VersionR_Entities.FK__Customer___ModId__60924D76", "Customer_Modules", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Versions__ModId__5EAA0504", "Versions")]
        public EntityCollection<Version> Versions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Version>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Versions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Version>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Versions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Role-Objekt.
        /// </summary>
        /// <param name="rId">Anfangswert der Eigenschaft RId.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        public static Role CreateRole(global::System.Int32 rId, global::System.String name)
        {
            Role role = new Role();
            role.RId = rId;
            role.Name = name;
            return role;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RId
        {
            get
            {
                return _RId;
            }
            set
            {
                if (_RId != value)
                {
                    OnRIdChanging(value);
                    ReportPropertyChanging("RId");
                    _RId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RId");
                    OnRIdChanged();
                }
            }
        }
        private global::System.Int32 _RId;
        partial void OnRIdChanging(global::System.Int32 value);
        partial void OnRIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Users__RId__6462DE5A", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("VersionR_Entities.FK__Users__RId__6462DE5A", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("VersionR_Entities.FK__Users__RId__6462DE5A", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues User-Objekt.
        /// </summary>
        /// <param name="uId">Anfangswert der Eigenschaft UId.</param>
        /// <param name="nickName">Anfangswert der Eigenschaft NickName.</param>
        /// <param name="eMail">Anfangswert der Eigenschaft EMail.</param>
        /// <param name="rId">Anfangswert der Eigenschaft RId.</param>
        /// <param name="pwHash">Anfangswert der Eigenschaft PwHash.</param>
        public static User CreateUser(global::System.Int32 uId, global::System.String nickName, global::System.String eMail, global::System.Int32 rId, global::System.String pwHash)
        {
            User user = new User();
            user.UId = uId;
            user.NickName = nickName;
            user.EMail = eMail;
            user.RId = rId;
            user.PwHash = pwHash;
            return user;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UId
        {
            get
            {
                return _UId;
            }
            set
            {
                if (_UId != value)
                {
                    OnUIdChanging(value);
                    ReportPropertyChanging("UId");
                    _UId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UId");
                    OnUIdChanged();
                }
            }
        }
        private global::System.Int32 _UId;
        partial void OnUIdChanging(global::System.Int32 value);
        partial void OnUIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RId
        {
            get
            {
                return _RId;
            }
            set
            {
                OnRIdChanging(value);
                ReportPropertyChanging("RId");
                _RId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RId");
                OnRIdChanged();
            }
        }
        private global::System.Int32 _RId;
        partial void OnRIdChanging(global::System.Int32 value);
        partial void OnRIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PwHash
        {
            get
            {
                return _PwHash;
            }
            set
            {
                OnPwHashChanging(value);
                ReportPropertyChanging("PwHash");
                _PwHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PwHash");
                OnPwHashChanged();
            }
        }
        private global::System.String _PwHash;
        partial void OnPwHashChanging(global::System.String value);
        partial void OnPwHashChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Customer_M__CmId__5F9E293D", "Customer_Modules")]
        public EntityCollection<Customer_Modules> Customer_Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Customer_Modules>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Customer_Modules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Customer_Modules>("VersionR_Entities.FK__Customer_M__CmId__5F9E293D", "Customer_Modules", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Downloads__CmId__627A95E8", "Downloads")]
        public EntityCollection<Download> Downloads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Download>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Downloads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Download>("VersionR_Entities.FK__Downloads__CmId__627A95E8", "Downloads", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Users__RId__6462DE5A", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("VersionR_Entities.FK__Users__RId__6462DE5A", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("VersionR_Entities.FK__Users__RId__6462DE5A", "Roles").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("VersionR_Entities.FK__Users__RId__6462DE5A", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("VersionR_Entities.FK__Users__RId__6462DE5A", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Versions__EmId__5DB5E0CB", "Versions")]
        public EntityCollection<Version> Versions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Version>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Versions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Version>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Versions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VersionR_Entities", Name="Version")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Version : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Version-Objekt.
        /// </summary>
        /// <param name="vrId">Anfangswert der Eigenschaft VrId.</param>
        /// <param name="relase">Anfangswert der Eigenschaft Relase.</param>
        /// <param name="subRelease">Anfangswert der Eigenschaft SubRelease.</param>
        /// <param name="buildId">Anfangswert der Eigenschaft BuildId.</param>
        /// <param name="platform">Anfangswert der Eigenschaft Platform.</param>
        /// <param name="filename">Anfangswert der Eigenschaft Filename.</param>
        /// <param name="releaseDate">Anfangswert der Eigenschaft ReleaseDate.</param>
        /// <param name="emId">Anfangswert der Eigenschaft EmId.</param>
        /// <param name="modId">Anfangswert der Eigenschaft ModId.</param>
        public static Version CreateVersion(global::System.Int32 vrId, global::System.Byte relase, global::System.Byte subRelease, global::System.String buildId, global::System.String platform, global::System.String filename, global::System.DateTime releaseDate, global::System.Int32 emId, global::System.Int32 modId)
        {
            Version version = new Version();
            version.VrId = vrId;
            version.Relase = relase;
            version.SubRelease = subRelease;
            version.BuildId = buildId;
            version.Platform = platform;
            version.Filename = filename;
            version.ReleaseDate = releaseDate;
            version.EmId = emId;
            version.ModId = modId;
            return version;
        }

        #endregion

        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VrId
        {
            get
            {
                return _VrId;
            }
            set
            {
                if (_VrId != value)
                {
                    OnVrIdChanging(value);
                    ReportPropertyChanging("VrId");
                    _VrId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VrId");
                    OnVrIdChanged();
                }
            }
        }
        private global::System.Int32 _VrId;
        partial void OnVrIdChanging(global::System.Int32 value);
        partial void OnVrIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Relase
        {
            get
            {
                return _Relase;
            }
            set
            {
                OnRelaseChanging(value);
                ReportPropertyChanging("Relase");
                _Relase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Relase");
                OnRelaseChanged();
            }
        }
        private global::System.Byte _Relase;
        partial void OnRelaseChanging(global::System.Byte value);
        partial void OnRelaseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte SubRelease
        {
            get
            {
                return _SubRelease;
            }
            set
            {
                OnSubReleaseChanging(value);
                ReportPropertyChanging("SubRelease");
                _SubRelease = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubRelease");
                OnSubReleaseChanged();
            }
        }
        private global::System.Byte _SubRelease;
        partial void OnSubReleaseChanging(global::System.Byte value);
        partial void OnSubReleaseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BuildId
        {
            get
            {
                return _BuildId;
            }
            set
            {
                OnBuildIdChanging(value);
                ReportPropertyChanging("BuildId");
                _BuildId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BuildId");
                OnBuildIdChanged();
            }
        }
        private global::System.String _BuildId;
        partial void OnBuildIdChanging(global::System.String value);
        partial void OnBuildIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Platform
        {
            get
            {
                return _Platform;
            }
            set
            {
                OnPlatformChanging(value);
                ReportPropertyChanging("Platform");
                _Platform = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Platform");
                OnPlatformChanged();
            }
        }
        private global::System.String _Platform;
        partial void OnPlatformChanging(global::System.String value);
        partial void OnPlatformChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Filename
        {
            get
            {
                return _Filename;
            }
            set
            {
                OnFilenameChanging(value);
                ReportPropertyChanging("Filename");
                _Filename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Filename");
                OnFilenameChanged();
            }
        }
        private global::System.String _Filename;
        partial void OnFilenameChanging(global::System.String value);
        partial void OnFilenameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReleaseDate
        {
            get
            {
                return _ReleaseDate;
            }
            set
            {
                OnReleaseDateChanging(value);
                ReportPropertyChanging("ReleaseDate");
                _ReleaseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReleaseDate");
                OnReleaseDateChanged();
            }
        }
        private global::System.DateTime _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.DateTime value);
        partial void OnReleaseDateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmId
        {
            get
            {
                return _EmId;
            }
            set
            {
                OnEmIdChanging(value);
                ReportPropertyChanging("EmId");
                _EmId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmId");
                OnEmIdChanged();
            }
        }
        private global::System.Int32 _EmId;
        partial void OnEmIdChanging(global::System.Int32 value);
        partial void OnEmIdChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModId
        {
            get
            {
                return _ModId;
            }
            set
            {
                OnModIdChanging(value);
                ReportPropertyChanging("ModId");
                _ModId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModId");
                OnModIdChanged();
            }
        }
        private global::System.Int32 _ModId;
        partial void OnModIdChanging(global::System.Int32 value);
        partial void OnModIdChanged();

        #endregion

    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Downloads__VrId__618671AF", "Downloads")]
        public EntityCollection<Download> Downloads
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Download>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Downloads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Download>("VersionR_Entities.FK__Downloads__VrId__618671AF", "Downloads", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Manuals__VrId__636EBA21", "Manuals")]
        public EntityCollection<Manual> Manuals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Manual>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Manuals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Manual>("VersionR_Entities.FK__Manuals__VrId__636EBA21", "Manuals", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Versions__ModId__5EAA0504", "Modules")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Modules").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Modules").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Modules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("VersionR_Entities.FK__Versions__ModId__5EAA0504", "Modules", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VersionR_Entities", "FK__Versions__EmId__5DB5E0CB", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Users").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("VersionR_Entities.FK__Versions__EmId__5DB5E0CB", "Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
